# Generated by Django 3.1.1 on 2020-11-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='image',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='team_pics'),
        ),
    ]
