# Generated by Django 3.1.1 on 2020-11-10 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_remove_meeting_team'),
        ('teams', '0002_auto_20201110_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='meetings',
            field=models.ManyToManyField(to='meeting.Meeting'),
        ),
    ]
