# Generated by Django 3.1.1 on 2020-11-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        ('teams', '0003_team_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='task_list',
            field=models.ManyToManyField(to='todo.Task'),
        ),
    ]
