# Generated by Django 3.1.1 on 2020-11-12 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
        ('teams', '0005_auto_20201112_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='task_list',
        ),
        migrations.AddField(
            model_name='team',
            name='task_list',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, to='todo.tasklist'),
            preserve_default=False,
        ),
    ]
