# Generated by Django 3.1.1 on 2020-11-04 09:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
                ('request_type', models.CharField(choices=[('T', 'Training'), ('A', 'Assessment')], max_length=4)),
                ('image', models.ImageField(upload_to='request_pics')),
                ('start_time', models.DateTimeField()),
                ('granted', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('user', models.ManyToManyField(related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
