# Generated by Django 3.1.1 on 2020-11-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerequest',
            name='request_type',
            field=models.CharField(blank=True, choices=[('T', 'Training'), ('A', 'Assessment')], max_length=4, null=True),
        ),
    ]
