# Generated by Django 3.1.1 on 2020-11-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_request', '0002_auto_20201104_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='request_pics'),
        ),
    ]
