# Generated by Django 3.1.1 on 2020-11-04 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance_request', '0003_auto_20201104_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerequest',
            name='user',
        ),
        migrations.AddField(
            model_name='attendancerequest',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
