# Generated by Django 3.1.1 on 2020-11-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_request', '0006_auto_20201104_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerequest',
            name='request_type',
            field=models.CharField(blank=True, choices=[('Training', 'Training'), ('Assessment', 'Assessment')], max_length=20, null=True),
        ),
    ]
