# Generated by Django 3.1.1 on 2020-09-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0003_auto_20200926_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='next_level',
            field=models.CharField(default='Level 1', max_length=50),
            preserve_default=False,
        ),
    ]
