# Generated by Django 3.1.1 on 2020-09-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_event_next_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
            preserve_default=False,
        ),
    ]
