# Generated by Django 3.1.1 on 2020-10-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0005_event_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
