# Generated by Django 3.1.1 on 2020-10-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_auto_20201013_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='inter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='event',
            name='tenth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
