# Generated by Django 3.1.1 on 2020-10-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0007_auto_20201016_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddLatestNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_date', models.DateTimeField()),
                ('post_data', models.TextField()),
            ],
        ),
    ]
