# Generated by Django 3.1.1 on 2020-10-22 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_addlatestnews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addlatestnews',
            old_name='end_date',
            new_name='end_time',
        ),
    ]
