# Generated by Django 3.1.1 on 2020-10-22 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_auto_20201022_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='addlatestnews',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
