# Generated by Django 3.1.1 on 2020-10-24 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0010_addlatestnews_created_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
