# Generated by Django 3.1.1 on 2020-09-24 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200923_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementDrives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package', models.CharField(max_length=10)),
                ('levels', models.IntegerField()),
                ('current_level', models.CharField(choices=[('a', 'Attempting'), ('p', 'Passed'), ('f', 'Failed')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='backlogs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='cgpa',
            field=models.CharField(default=0.0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='is_cr',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='num_drives_attempt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='percentage',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='places',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='jobs',
            field=models.ManyToManyField(to='user.PlacementDrives'),
        ),
    ]
