# Generated by Django 3.1.1 on 2020-09-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200924_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_cr',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='jobs',
        ),
        migrations.AlterField(
            model_name='profile',
            name='section',
            field=models.CharField(choices=[('B01', 'B01'), ('B02', 'B02'), ('B03', 'B03'), ('B04', 'B04'), ('B05', 'B05'), ('B06', 'B06'), ('B07', 'B07'), ('B08', 'B08'), ('B09', 'B09'), ('B10', 'B11'), ('B12', 'B12'), ('B13', 'B13'), ('B14', 'B14')], max_length=4),
        ),
        migrations.DeleteModel(
            name='PlacementDrives',
        ),
    ]
