# Generated by Django 3.1.1 on 2020-09-26 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200926_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='backlogs',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='num_drives_attempt',
            field=models.IntegerField(default=0),
        ),
    ]
