# Generated by Django 3.1.1 on 2020-09-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200926_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='percentage',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='places',
        ),
    ]
