# Generated by Django 3.1.1 on 2020-09-27 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200927_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cgpa',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
