# Generated by Django 3.1.1 on 2020-10-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0006_auto_20201013_1725'),
        ('user', '0010_auto_20200927_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_events',
            field=models.ManyToManyField(to='calendarapp.Event'),
        ),
    ]
