# Generated by Django 3.1.1 on 2020-10-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_profile_current_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='inter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='tenth',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
    ]
