# Generated by Django 3.1.1 on 2020-11-04 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20201016_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unique_string',
            field=models.CharField(default='1xcVu0I', max_length=15),
        ),
    ]
