# Generated by Django 3.1.1 on 2020-11-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('user', '0013_profile_unique_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='team',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
